# 🗺️ 네이버 플레이스 크롤링

제주도 관광지/음식점/숙박 데이터를 네이버 플레이스에서 크롤링합니다.

## 수집 데이터
- 장소명
- 평점 ⭐
- 리뷰 수
- 가격대 (음식점)
- 카테고리
- 영업시간
- 위치 (주소, 위도/경도)

## 1. 설정 및 라이브러리 설치

In [1]:
import asyncio
import random
import json
import re
from pathlib import Path
from typing import Dict, List, Optional, Any
from dataclasses import dataclass, asdict
from datetime import datetime

import pandas as pd
from tqdm.auto import tqdm  # notebook 대신 auto 사용 (호환성 좋음)
from playwright.async_api import async_playwright, Page, Browser

# Jupyter에서 async 실행을 위한 설정
import nest_asyncio
nest_asyncio.apply()

# 데이터 저장 경로
DATA_DIR = Path("../../data")
DATA_DIR.mkdir(exist_ok=True)

print(f"✅ 라이브러리 로드 완료")
print(f"📁 데이터 저장 경로: {DATA_DIR.absolute()}")

/Users/ohyooseok/miniconda3/envs/jeju_chatbot/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

✅ 라이브러리 로드 완료
📁 데이터 저장 경로: /Users/ohyooseok/PAI_SQL/jeju-travel-chatbot/backend/scripts/crawling/../../data

## 2. 데이터 클래스 및 크롤링 설정

In [2]:
@dataclass
class NaverPlace:
    """네이버 플레이스 데이터"""
    name: str                          # 장소명
    category: str                      # 카테고리
    address: str                       # 주소
    rating: Optional[float] = None     # 평점 (0~5)
    review_count: Optional[int] = None # 리뷰 수
    price_range: Optional[str] = None  # 가격대
    lat: Optional[float] = None        # 위도
    lng: Optional[float] = None        # 경도
    business_hours: Optional[str] = None
    naver_id: Optional[str] = None
    url: Optional[str] = None
    
    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

# 크롤링 설정
CONFIG = {
    "delay_min": 2.0,        # 최소 대기 시간 (초)
    "delay_max": 4.0,        # 최대 대기 시간 (초)
    "max_retries": 3,        # 최대 재시도 횟수
    "timeout": 30000,        # 타임아웃 (ms)
    "headless": False,       # 브라우저 보이게 (디버깅용)
}

# User-Agent 리스트
USER_AGENTS = [
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/120.0.0.0 Safari/537.36",
]

# 검색 키워드 (세분화해서 더 많은 데이터 수집)
SEARCH_KEYWORDS = [
    # === 지역별 맛집 ===
    "제주시 맛집", "서귀포 맛집", "애월 맛집", "함덕 맛집",
    "중문 맛집", "성산 맛집", "한림 맛집", "조천 맛집",
    "우도 맛집", "협재 맛집",
    
    # === 음식 종류별 ===
    "제주 흑돼지", "제주 횟집", "제주 고기국수", "제주 갈치조림",
    "제주 해물탕", "제주 전복죽", "제주 삼겹살", "제주 회",
    "제주 해산물", "제주 한식", "제주 분식",
    
    # === 지역별 카페 ===
    "제주시 카페", "서귀포 카페", "애월 카페", "함덕 카페",
    "중문 카페", "성산 카페", "협재 카페", "한림 카페",
    "제주 오션뷰 카페", "제주 감성카페",
    
    # === 관광/명소 ===
    "제주 관광지", "제주 오름", "제주 해변", "제주 폭포",
    "제주 박물관", "제주 테마파크",
    
    # === 숙박 ===
    "제주 호텔", "제주 펜션", "제주 게스트하우스", "제주 리조트",
    "서귀포 호텔", "중문 리조트",
]

print(f"✅ 설정 완료")
print(f"🔍 검색 키워드: {len(SEARCH_KEYWORDS)}개")

✅ 설정 완료
🔍 검색 키워드: 43개

In [3]:
async def random_delay():
    """랜덤 대기 (Rate Limiting)"""
    delay = random.uniform(CONFIG["delay_min"], CONFIG["delay_max"])
    await asyncio.sleep(delay)


async def create_browser():
    """Playwright 브라우저 생성"""
    playwright = await async_playwright().start()
    browser = await playwright.chromium.launch(headless=CONFIG["headless"])
    context = await browser.new_context(
        user_agent=random.choice(USER_AGENTS),
        viewport={"width": 1920, "height": 1080},
    )
    page = await context.new_page()
    return playwright, browser, page


async def close_browser(playwright, browser):
    """브라우저 종료"""
    await browser.close()
    await playwright.stop()


print("✅ 기본 함수 정의 완료")

✅ 기본 함수 정의 완료

In [4]:
from urllib.parse import quote

async def search_naver_map(page: Page, keyword: str, max_items: int = 50) -> List[Dict]:
    """네이버 지도에서 장소 검색 (스크롤해서 많은 결과 수집)"""
    results = []
    
    # 네이버 모바일 지도 검색 URL
    encoded_keyword = quote(keyword)
    search_url = f"https://m.map.naver.com/search2/search.naver?query={encoded_keyword}&sm=hty&style=v5"
    
    try:
        await page.goto(search_url, timeout=CONFIG["timeout"])
        await page.wait_for_load_state("networkidle", timeout=CONFIG["timeout"])
        await asyncio.sleep(3)
        
        # 스크롤해서 더 많은 결과 로드 (max_items까지)
        prev_count = 0
        scroll_attempts = 0
        max_scroll_attempts = 20  # 최대 스크롤 횟수
        
        while scroll_attempts < max_scroll_attempts:
            # 현재 아이템 수 확인 - 새 셀렉터 사용
            items = await page.query_selector_all('li[class*="_list_item"]')
            current_count = len(items)
            
            if current_count >= max_items:
                break
            
            if current_count == prev_count:
                scroll_attempts += 1
                if scroll_attempts >= 3:  # 3번 연속 변화 없으면 종료
                    break
            else:
                scroll_attempts = 0
            
            prev_count = current_count
            
            # 스크롤 다운
            await page.evaluate("window.scrollTo(0, document.body.scrollHeight)")
            await asyncio.sleep(1)
        
        # 검색 결과 수집 - 새 셀렉터
        items = await page.query_selector_all('li[class*="_list_item"]')
        print(f"   네이버 지도에서 {len(items)}개 발견")
        
        seen_names = set()
        
        for item in items[:max_items]:
            try:
                # 장소명 (새 셀렉터)
                name_elem = await item.query_selector('strong[class*="_item_name"]')
                if not name_elem:
                    continue
                name = await name_elem.inner_text()
                name = name.strip()
                
                if not name or name in seen_names:
                    continue
                seen_names.add(name)
                
                # place_id 추출 - URL에서 추출
                naver_id = None
                link_elem = await item.query_selector('a[href*="place.naver.com/place/"]')
                if link_elem:
                    href = await link_elem.get_attribute('href')
                    id_match = re.search(r'/place/(\d+)', href)
                    if id_match:
                        naver_id = id_match.group(1)
                
                # 카테고리 (새 셀렉터)
                category = keyword
                try:
                    cat_elem = await item.query_selector('em[class*="_item_category"]')
                    if cat_elem:
                        category = await cat_elem.inner_text()
                        category = category.strip()
                except:
                    pass
                
                # 주소 (새 셀렉터)
                address = ""
                try:
                    addr_elem = await item.query_selector('button[class*="_item_address"]')
                    if addr_elem:
                        address = await addr_elem.inner_text()
                        # "주소보기" 텍스트 제거
                        address = address.replace("주소보기", "").strip()
                except:
                    pass
                
                # URL 생성
                url = f"https://m.place.naver.com/restaurant/{naver_id}/home" if naver_id else ""
                
                results.append({
                    "naver_id": naver_id,
                    "name": name,
                    "category": category if category else keyword,
                    "rating": None,  # 상세 페이지에서 수집
                    "review_count": 0,
                    "address": address,
                    "url": url,
                    "keyword": keyword,
                })
                
            except Exception as e:
                continue
                
    except Exception as e:
        print(f"❌ 검색 실패 ({keyword}): {e}")
    
    return results


print("✅ 검색 함수 정의 완료 (네이버 통합검색 버전)")

✅ 검색 함수 정의 완료 (네이버 통합검색 버전)

## 3-2. 상세 페이지 크롤링 (2단계)

통합검색에서 수집한 URL로 상세 페이지를 방문해서 **리뷰 수, 평점, 주소** 등을 수집합니다.

In [5]:
async def resolve_tivan_url(page: Page, tivan_url: str) -> Optional[str]:
    """tivan.naver.com 리다이렉트 URL에서 실제 place_id 추출"""
    if not tivan_url or 'tivan.naver.com' not in tivan_url:
        return None
    
    try:
        await page.goto(tivan_url, timeout=CONFIG["timeout"], wait_until="domcontentloaded")
        await asyncio.sleep(2)
        
        # 리다이렉트된 URL에서 place_id 추출
        current_url = page.url
        id_match = re.search(r'/place/(\d+)', current_url)
        if id_match:
            return id_match.group(1)
        
        # m.place.naver.com 형태도 체크
        id_match = re.search(r'/restaurant/(\d+)', current_url)
        if id_match:
            return id_match.group(1)
            
    except Exception as e:
        print(f"      ⚠️ 리다이렉트 URL 처리 실패: {e}")
    
    return None


async def get_menu_info(page: Page, place_id: str) -> Dict:
    """메뉴 탭에서 메뉴 정보 수집"""
    menu_info = {
        "menus": [],           # 메뉴 리스트 [{name, price, category}]
        "min_price": None,     # 최저 가격
        "max_price": None,     # 최고 가격
        "price_range": "",     # 가격대 (저렴/보통/비쌈/고급)
    }
    
    menu_url = f"https://m.place.naver.com/restaurant/{place_id}/menu/list"
    
    try:
        await page.goto(menu_url, timeout=CONFIG["timeout"])
        await page.wait_for_load_state("networkidle", timeout=CONFIG["timeout"])
        await asyncio.sleep(1)
        
        # 메뉴 아이템들 찾기
        menu_items = await page.query_selector_all('.E2jtL, .menu_item, [class*="MenuItem"]')
        
        prices = []
        for item in menu_items[:10]:  # 상위 10개 메뉴
            try:
                # 메뉴명
                name_elem = await item.query_selector('.lPzHi, .menu_name, [class*="name"]')
                name = await name_elem.inner_text() if name_elem else ""
                
                # 가격
                price_elem = await item.query_selector('.GXS1X, .menu_price, [class*="price"]')
                price_text = await price_elem.inner_text() if price_elem else ""
                
                # 가격 숫자 추출
                price_match = re.search(r'(\d[\d,]*)', price_text)
                price = int(price_match.group(1).replace(',', '')) if price_match else None
                
                if name and price:
                    # 메뉴 카테고리 추정 (가격 기반)
                    if price < 5000:
                        category = "음료/사이드"
                    elif price < 15000:
                        category = "단품"
                    else:
                        category = "메인"
                    
                    menu_info["menus"].append({
                        "name": name.strip(),
                        "price": price,
                        "category": category
                    })
                    prices.append(price)
            except:
                continue
        
        # 최저/최고 가격 계산
        if prices:
            menu_info["min_price"] = min(prices)
            menu_info["max_price"] = max(prices)
            
            # 가격대는 메인 메뉴 기준 (1만원 이상인 것들의 평균)
            main_prices = [p for p in prices if p >= 10000]
            if main_prices:
                avg_main = sum(main_prices) // len(main_prices)
            else:
                avg_main = sum(prices) // len(prices)
            
            if avg_main < 12000:
                menu_info["price_range"] = "저렴"
            elif avg_main < 25000:
                menu_info["price_range"] = "보통"
            elif avg_main < 50000:
                menu_info["price_range"] = "비쌈"
            else:
                menu_info["price_range"] = "고급"
                
    except Exception as e:
        pass  # 메뉴 정보 없으면 무시
    
    return menu_info


async def get_facility_info(page: Page, place_id: str) -> Dict:
    """정보 탭에서 편의시설 정보 수집"""
    facility = {
        "phone": "",
        "parking": False,
        "kid_friendly": False,
        "wheelchair": False,
        "pet_friendly": False,
        "reservation": False,
        "wifi": False,
    }
    
    info_url = f"https://m.place.naver.com/restaurant/{place_id}/information"
    
    try:
        await page.goto(info_url, timeout=CONFIG["timeout"])
        await page.wait_for_load_state("networkidle", timeout=CONFIG["timeout"])
        await asyncio.sleep(1)
        
        # 전체 텍스트에서 편의시설 키워드 찾기
        full_text = await page.inner_text('body')
        full_text_lower = full_text.lower()
        
        # 전화번호
        phone_match = re.search(r'(0\d{1,2}[-.\s]?\d{3,4}[-.\s]?\d{4})', full_text)
        if phone_match:
            facility["phone"] = phone_match.group(1)
        
        # 편의시설 키워드 매칭
        if '주차' in full_text and ('가능' in full_text or '있음' in full_text or '무료' in full_text):
            facility["parking"] = True
        if '유아' in full_text or '아이' in full_text or '키즈' in full_text:
            facility["kid_friendly"] = True
        if '휠체어' in full_text or '장애인' in full_text:
            facility["wheelchair"] = True
        if '반려' in full_text or '애견' in full_text or '펫' in full_text:
            facility["pet_friendly"] = True
        if '예약' in full_text:
            facility["reservation"] = True
        if '와이파이' in full_text or 'wifi' in full_text_lower or 'wi-fi' in full_text_lower:
            facility["wifi"] = True
            
    except Exception as e:
        pass  # 정보 없으면 무시
    
    return facility


async def get_place_details(page: Page, place_id: str) -> Dict:
    """네이버 플레이스 상세 페이지에서 정보 수집 (홈 + 메뉴 + 정보 + 위경도)"""
    details = {
        "rating": None,
        "review_count": 0,
        "address": "",
        "business_hours": "",
        # 위치 정보 (새로 추가!)
        "lat": None,
        "lng": None,
        # 메뉴 정보
        "min_price": None,
        "max_price": None,
        "price_range": "",
        "menus": [],
        # 편의시설
        "phone": "",
        "parking": False,
        "kid_friendly": False,
        "wheelchair": False,
        "pet_friendly": False,
        "reservation": False,
        "wifi": False,
    }
    
    if not place_id:
        return details
    
    # 1. 홈 탭 - 기본 정보
    detail_url = f"https://m.place.naver.com/restaurant/{place_id}/home"
    
    try:
        await page.goto(detail_url, timeout=CONFIG["timeout"])
        await page.wait_for_load_state("networkidle", timeout=CONFIG["timeout"])
        await asyncio.sleep(2)
        
        # 평점
        try:
            rating_elem = await page.query_selector('.PXMot, .LXIwF')
            if rating_elem:
                rating_text = await rating_elem.inner_text()
                rating_match = re.search(r'(\d+\.?\d*)', rating_text)
                if rating_match:
                    details["rating"] = float(rating_match.group(1))
        except:
            pass
        
        # 리뷰 수 - 여러 방법 시도
        try:
            # 방법 1: 전체 페이지 텍스트에서 "리뷰 숫자" 패턴 찾기
            full_text = await page.inner_text('body')
            
            # "방문자리뷰 1,234" 또는 "리뷰 1,234" 패턴
            review_patterns = [
                r'방문자리뷰\s*(\d[\d,]*)',
                r'리뷰\s*(\d[\d,]*)',
                r'(\d[\d,]*)\s*리뷰',
            ]
            
            for pattern in review_patterns:
                match = re.search(pattern, full_text)
                if match:
                    count_str = match.group(1).replace(',', '')
                    if count_str.isdigit():
                        details["review_count"] = int(count_str)
                        break
        except:
            pass
        
        # 주소
        try:
            addr_elem = await page.query_selector('.LDgIH, .IH7VW')
            if addr_elem:
                details["address"] = await addr_elem.inner_text()
        except:
            pass
        
        # 영업시간
        try:
            hours_elem = await page.query_selector('.A_cdD, .MxgIj')
            if hours_elem:
                details["business_hours"] = await hours_elem.inner_text()
        except:
            pass
        
        # 위경도 추출 (__NEXT_DATA__ 또는 script에서)
        try:
            # 방법 1: __NEXT_DATA__ script 태그에서 추출
            script_content = await page.evaluate('''() => {
                const script = document.querySelector('script#__NEXT_DATA__');
                return script ? script.textContent : null;
            }''')
            
            if script_content:
                import json
                next_data = json.loads(script_content)
                # 좌표 정보 탐색 (구조가 다를 수 있음)
                props = next_data.get("props", {}).get("pageProps", {})
                
                # 여러 가능한 경로 탐색
                coord_paths = [
                    lambda p: (p.get("initialState", {}).get("place", {}).get("coordinate", {})),
                    lambda p: (p.get("initialState", {}).get("common", {}).get("coordinate", {})),
                    lambda p: (p.get("place", {}).get("coordinate", {})),
                    lambda p: (p.get("placeDetail", {}).get("coordinate", {})),
                ]
                
                for path_fn in coord_paths:
                    try:
                        coord = path_fn(props)
                        if coord and "y" in coord and "x" in coord:
                            details["lat"] = float(coord["y"])
                            details["lng"] = float(coord["x"])
                            break
                    except:
                        continue
            
            # 방법 2: 페이지 HTML에서 좌표 패턴 직접 검색
            if details["lat"] is None:
                html = await page.content()
                # "y":33.xxx,"x":126.xxx 패턴 찾기
                coord_match = re.search(r'"y"\s*:\s*(33\.\d+)\s*,\s*"x"\s*:\s*(126\.\d+)', html)
                if coord_match:
                    details["lat"] = float(coord_match.group(1))
                    details["lng"] = float(coord_match.group(2))
                
                # 또는 lat/lng 패턴
                if details["lat"] is None:
                    lat_match = re.search(r'"lat(?:itude)?"\s*:\s*(33\.\d+)', html)
                    lng_match = re.search(r'"lng|longitude"\s*:\s*(126\.\d+)', html)
                    if lat_match and lng_match:
                        details["lat"] = float(lat_match.group(1))
                        details["lng"] = float(lng_match.group(1))
        except Exception as e:
            pass  # 위경도 추출 실패해도 계속 진행
            
    except Exception as e:
        print(f"   ⚠️ 홈 탭 오류 ({place_id}): {e}")
    
    # 2. 메뉴 탭 - 메뉴/가격 정보
    try:
        menu_info = await get_menu_info(page, place_id)
        details.update(menu_info)
    except Exception as e:
        pass
    
    # 3. 정보 탭 - 편의시설 정보
    try:
        facility_info = await get_facility_info(page, place_id)
        details.update(facility_info)
    except Exception as e:
        pass
    
    return details


async def enrich_place_data(page: Page, places: List[Dict], show_progress: bool = True) -> List[Dict]:
    """수집된 장소 데이터에 상세 정보 추가"""
    enriched = []
    
    # tqdm 진행 표시
    iterator = tqdm(places, desc="상세 정보 수집", unit="장소") if show_progress else places
    
    for place in iterator:
        if show_progress:
            iterator.set_postfix({"현재": place['name'][:10]})
        
        # place_id 추출
        place_id = place.get('naver_id')
        url = place.get('url', '')
        
        # URL에서 place_id 추출 시도
        if not place_id and url:
            id_match = re.search(r'/place/(\d+)', url)
            if id_match:
                place_id = id_match.group(1)
        
        # tivan.naver.com 리다이렉트 URL 처리
        if not place_id and 'tivan.naver.com' in url:
            print(f"      🔗 리다이렉트 URL 처리 중...")
            place_id = await resolve_tivan_url(page, url)
            if place_id:
                print(f"      ✅ place_id 추출: {place_id}")
        
        if place_id:
            details = await get_place_details(page, place_id)
            place.update({
                "naver_id": place_id,
                "rating": details["rating"] or place.get("rating"),
                "review_count": details["review_count"],
                "address": details["address"] or place.get("address"),
                "business_hours": details["business_hours"],
                # 위치 정보 (새로 추가!)
                "lat": details.get("lat"),
                "lng": details.get("lng"),
                # 메뉴 정보
                "min_price": details.get("min_price"),
                "max_price": details.get("max_price"),
                "price_range": details.get("price_range", ""),
                "menus": details.get("menus", []),
                # 편의시설
                "phone": details.get("phone", ""),
                "parking": details.get("parking", False),
                "kid_friendly": details.get("kid_friendly", False),
                "wheelchair": details.get("wheelchair", False),
                "pet_friendly": details.get("pet_friendly", False),
                "reservation": details.get("reservation", False),
                "wifi": details.get("wifi", False),
            })
        else:
            print(f"      ⚠️ place_id를 찾을 수 없음")
        
        enriched.append(place)
        await random_delay()  # Rate limiting
    
    return enriched


print("✅ 상세 페이지 크롤링 함수 정의 완료")

✅ 상세 페이지 크롤링 함수 정의 완료

### 🔧 디버깅: 현재 페이지 HTML 구조 확인

셀렉터가 안 맞으면 아래 셀을 실행해서 실제 HTML 구조를 확인하세요.

In [6]:
async def debug_page_structure():
    """네이버 지도 페이지 구조 디버깅"""
    print("🔍 네이버 지도 페이지 구조 분석 중...")
    
    playwright, browser, page = await create_browser()
    
    try:
        keyword = "제주 맛집"
        # 네이버 모바일 지도 검색 URL
        encoded_keyword = quote(keyword)
        search_url = f"https://m.map.naver.com/search2/search.naver?query={encoded_keyword}&sm=hty&style=v5"
        
        print(f"📍 URL: {search_url}")
        
        await page.goto(search_url, timeout=CONFIG["timeout"])
        await page.wait_for_load_state("networkidle", timeout=CONFIG["timeout"])
        await asyncio.sleep(5)  # JavaScript 완전 렌더링 대기
        
        # 스크롤 3번
        print("📜 스크롤 중...")
        for _ in range(3):
            await page.evaluate("window.scrollTo(0, document.body.scrollHeight)")
            await asyncio.sleep(1)
        
        # 페이지 제목
        title = await page.title()
        print(f"📄 페이지 제목: {title}")
        
        # 다양한 셀렉터 테스트 (네이버 지도)
        selectors_to_test = [
            ('li._item', 'li._item'),
            ('li[data-id]', 'li[data-id]'),
            ('.search_item', 'search_item'),
            ('.item_info', 'item_info'),
            ('[class*="item"]', 'item 포함'),
            ('[class*="place"]', 'place 포함'),
            ('[class*="list"]', 'list 포함'),
            ('ul li', 'ul li'),
            ('a[href*="place"]', 'place 링크'),
        ]
        
        print("\n🧪 셀렉터 테스트:")
        for selector, name in selectors_to_test:
            try:
                items = await page.query_selector_all(selector)
                if items:
                    print(f"   ✅ {name}: {len(items)}개")
                    if len(items) > 0:
                        first = items[0]
                        try:
                            text = await first.inner_text()
                            print(f"      예시: {text[:50]}...")
                        except:
                            pass
                else:
                    print(f"   ❌ {name}: 0개")
            except:
                print(f"   ❌ {name}: 오류")
        
        # HTML 저장
        print("\n📝 페이지 HTML 저장...")
        html = await page.content()
        with open(DATA_DIR / "debug_page.html", "w", encoding="utf-8") as f:
            f.write(html)
        print(f"   저장됨: {DATA_DIR / 'debug_page.html'}")
        
        # 10초간 브라우저 유지
        print("\n⏳ 10초간 브라우저 유지...")
        await asyncio.sleep(10)
        
    finally:
        await close_browser(playwright, browser)
    
    print("\n✅ 디버깅 완료!")


# 디버깅 실행
loop = asyncio.get_event_loop()
loop.run_until_complete(debug_page_structure())

🔍 네이버 지도 페이지 구조 분석 중...
📍 URL: https://m.map.naver.com/search2/search.naver?query=%EC%A0%9C%EC%A3%BC%20%EB%A7%9B%EC%A7%91&sm=hty&style=v5
📜 스크롤 중...
📄 페이지 제목: 네이버지도

🧪 셀렉터 테스트:
   ❌ li._item: 0개
   ❌ li[data-id]: 0개
   ❌ search_item: 0개
   ❌ item_info: 0개
   ✅ item 포함: 1262개
      예시: 지도...
   ❌ place 포함: 0개
   ✅ list 포함: 232개
      예시: 지도
길찾기
네이버 통합검색
버스
지하철
네이버 통합검색
교통정보...
   ✅ ul li: 86개
      예시: 지도...
   ✅ place 링크: 301개
      예시: 신규장소 등록...

📝 페이지 HTML 저장...
   저장됨: ../../data/debug_page.html

⏳ 10초간 브라우저 유지...

✅ 디버깅 완료!

## 4. 테스트 크롤링 (10개)

In [6]:
async def test_crawling_with_details():
    """2단계 크롤링 테스트 (네이버 지도 + 상세페이지)"""
    print("🚀 2단계 크롤링 테스트 시작...")
    
    playwright, browser, page = await create_browser()
    
    try:
        # 1단계: 네이버 지도에서 장소 리스트 수집
        keyword = "제주 맛집"
        print(f"\n📌 1단계: 네이버 지도에서 장소 리스트 수집")
        print(f"   🔍 검색: {keyword}")
        
        results = await search_naver_map(page, keyword, max_items=20)
        print(f"   검색 결과: {len(results)}개")
        
        if not results:
            return []
        
        # 2단계: 상세 페이지에서 추가 정보 수집 (처음 5개만 테스트)
        print(f"\n📌 2단계: 상세 페이지에서 리뷰/평점 수집 (5개 테스트)")
        test_results = results[:5]  # 처음 5개만 테스트
        enriched = await enrich_place_data(page, test_results)
        
        return enriched
        
    finally:
        await close_browser(playwright, browser)


# 테스트 실행
loop = asyncio.get_event_loop()
search_results = loop.run_until_complete(test_crawling_with_details())

print(f"\n✅ 테스트 완료! {len(search_results)}개 수집")

🚀 2단계 크롤링 테스트 시작...

📌 1단계: 네이버 지도에서 장소 리스트 수집
   🔍 검색: 제주 맛집
   네이버 지도에서 75개 발견
   검색 결과: 20개

📌 2단계: 상세 페이지에서 리뷰/평점 수집 (5개 테스트)

상세 정보 수집: 100%|██████████| 5/5 [01:19<00:00, 15.86s/장소, 현재=신제주보말칼국수 제]

✅ 테스트 완료! 5개 수집

In [7]:
# 테스트 결과 확인
if search_results:
    df_search = pd.DataFrame(search_results)
    display(df_search.head(20))
else:
    print("❌ 검색 결과가 없습니다. 셀렉터를 확인해주세요.")

,naver_id,name,category,rating,review_count,address,url,keyword,business_hours,lat,...,max_price,price_range,menus,phone,parking,kid_friendly,wheelchair,pet_friendly,reservation,wifi
0,1883471138,도갈비,돼지고기구이,4.73,2450,제주 제주시 한라대학로 85 1층 도갈비,https://m.place.naver.com/restaurant/188347113...,제주 맛집,영업 중\n23:00에 영업 종료\n23시 0분에 영업 종료,33.476430,...,69000,비쌈,"[{'name': '제주갈비한판', 'price': 65000, 'category'...",,True,True,True,False,True,False
1,1556085331,서귀포 제주에인감귤밭 카페,"카페,디저트",2.00,2849,제주 서귀포시 호근서호로 20-14 서귀포카페 제주에인감귤밭,https://m.place.naver.com/restaurant/155608533...,제주 맛집,영업 종료\n내일 휴무\n내일 휴무,33.255333,...,27000,보통,"[{'name': '수제청만들기 클래스', 'price': 27000, 'categ...",,True,True,False,True,True,False
2,1398215720,수평선고등어쌈밥 제주본점,향토음식,1.00,1232,제주 제주시 서해안로 131 1층,https://m.place.naver.com/restaurant/139821572...,제주 맛집,영업 중\n21:30에 라스트오더\n21시 30분에 라스트오더,33.502867,...,40000,비쌈,"[{'name': '고등어 묵은지 쌈밥', 'price': 35000, 'categ...",,True,True,False,True,True,False
3,1339557107,카페 더 콘테나 제주,"카페,디저트",3.00,3120,제주 제주시 조천읍 함와로 513,https://m.place.naver.com/restaurant/133955710...,제주 맛집,영업 종료\n10:30에 영업 시작\n10시 30분에 영업 시작,33.495321,...,8500,저렴,"[{'name': '미니 귤케이크', 'price': 8500, 'category'...",,True,True,False,True,True,False
4,1815377666,신제주보말칼국수 제주본점,"칼국수,만두",4.57,4278,제주 제주시 선덕로5길 19 신제주 보말칼국수,https://m.place.naver.com/restaurant/181537766...,제주 맛집,영업 종료\n내일 휴무\n내일 휴무,33.485679,...,14000,보통,"[{'name': '보말칼국수(제주향토음식)', 'price': 11000, 'ca...",,True,True,False,False,True,False

## 5. 본 크롤링 (전체)

⚠️ 전체 크롤링은 시간이 오래 걸립니다. 중간 저장하면서 진행하세요.

In [6]:
def save_intermediate(data: List[Dict], prefix: str = "naver_places"):
    """중간 저장"""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filepath = DATA_DIR / f"{prefix}_{timestamp}.json"
    
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    print(f"💾 중간 저장: {filepath}")
    return filepath


async def full_crawling(keywords: List[str], max_per_keyword: int = 30, with_details: bool = True):
    """전체 크롤링 (검색 + 상세정보)"""
    all_results = []
    seen_ids = set()
    
    # 예상 시간 계산
    estimated_places = len(keywords) * max_per_keyword
    if with_details:
        estimated_time = (len(keywords) * 10) + (estimated_places * 15)
    else:
        estimated_time = len(keywords) * 10
    print(f"⏱️ 예상 시간: 약 {estimated_time // 60}분 (최대 {estimated_places}개 장소)")
    
    playwright, browser, page = await create_browser()
    
    try:
        # 1단계: 네이버 지도 검색
        print("\n📌 1단계: 네이버 지도 검색")
        for keyword in tqdm(keywords, desc="키워드 검색", unit="키워드"):
            results = await search_naver_map(page, keyword, max_items=max_per_keyword)
            
            for item in results[:max_per_keyword]:
                place_id = item.get("naver_id")
                if not place_id or place_id in seen_ids:
                    continue
                seen_ids.add(place_id)
                all_results.append(item)
            
            await random_delay()
        
        print(f"   ✅ {len(all_results)}개 장소 수집 완료")
        
        # 2단계: 상세 정보 수집
        if with_details and all_results:
            print("\n📌 2단계: 상세 정보 수집")
            all_results = await enrich_place_data(page, all_results, show_progress=True)
            
            # 중간 저장
            save_intermediate(all_results)
    
    finally:
        await close_browser(playwright, browser)
    
    return all_results


print("✅ 전체 크롤링 함수 정의 완료")

✅ 전체 크롤링 함수 정의 완료

In [7]:
# 🍽️ 맛집/카페만 재크롤링 (위경도 포함)
# 관광지, 숙박은 제외하고 맛집/카페만 크롤링합니다.

FOOD_CAFE_KEYWORDS = [
    # === 지역별 맛집 ===
    "제주시 맛집", "서귀포 맛집", "애월 맛집", "함덕 맛집",
    "중문 맛집", "성산 맛집", "한림 맛집", "조천 맛집",
    "우도 맛집", "협재 맛집",
    
    # === 음식 종류별 ===
    "제주 흑돼지", "제주 횟집", "제주 고기국수", "제주 갈치조림",
    "제주 해물탕", "제주 전복죽", "제주 삼겹살", "제주 회",
    "제주 해산물", "제주 한식", "제주 분식",
    
    # === 지역별 카페 ===
    "제주시 카페", "서귀포 카페", "애월 카페", "함덕 카페",
    "중문 카페", "성산 카페", "협재 카페", "한림 카페",
    "제주 오션뷰 카페", "제주 감성카페",
]

print(f"🍽️ 맛집/카페 키워드: {len(FOOD_CAFE_KEYWORDS)}개")
print(f"⏱️ 예상 시간: 약 {len(FOOD_CAFE_KEYWORDS) * 10 // 60}분 (1단계) + 상세정보 수집")

🍽️ 맛집/카페 키워드: 31개
⏱️ 예상 시간: 약 5분 (1단계) + 상세정보 수집

In [10]:
# 🚀 맛집/카페 크롤링 실행 (위경도 포함!)
# 이 셀을 실행하면 맛집/카페 데이터를 수집합니다.

loop = asyncio.get_event_loop()
food_cafe_data = loop.run_until_complete(full_crawling(FOOD_CAFE_KEYWORDS, max_per_keyword=30))

print(f"\n✅ 맛집/카페 크롤링 완료! 총 {len(food_cafe_data)}개 수집")

# 위경도 수집 통계
with_coords = sum(1 for d in food_cafe_data if d.get('lat') and d.get('lng'))
print(f"📍 위경도 있는 장소: {with_coords}개 ({with_coords/len(food_cafe_data)*100:.1f}%)")

⏱️ 예상 시간: 약 237분 (최대 930개 장소)

📌 1단계: 네이버 지도 검색

키워드 검색:   0%|          | 0/31 [00:00<?, ?키워드/s]

   네이버 지도에서 75개 발견

키워드 검색:   3%|▎         | 1/31 [00:10<05:27, 10.90s/키워드]

   네이버 지도에서 75개 발견

키워드 검색:   6%|▋         | 2/31 [00:21<05:10, 10.72s/키워드]

   네이버 지도에서 75개 발견

키워드 검색:  10%|▉         | 3/31 [00:29<04:31,  9.68s/키워드]

   네이버 지도에서 75개 발견

키워드 검색:  13%|█▎        | 4/31 [00:37<04:02,  8.99s/키워드]

   네이버 지도에서 75개 발견

키워드 검색:  16%|█▌        | 5/31 [00:46<03:54,  9.02s/키워드]

   네이버 지도에서 75개 발견

키워드 검색:  19%|█▉        | 6/31 [00:55<03:41,  8.85s/키워드]

   네이버 지도에서 75개 발견

키워드 검색:  23%|██▎       | 7/31 [01:03<03:22,  8.43s/키워드]

   네이버 지도에서 75개 발견

키워드 검색:  26%|██▌       | 8/31 [01:11<03:11,  8.32s/키워드]

   네이버 지도에서 75개 발견

키워드 검색:  29%|██▉       | 9/31 [01:19<03:04,  8.39s/키워드]

   네이버 지도에서 75개 발견

키워드 검색:  32%|███▏      | 10/31 [01:27<02:52,  8.21s/키워드]

   네이버 지도에서 75개 발견

키워드 검색:  35%|███▌      | 11/31 [01:36<02:48,  8.44s/키워드]

   네이버 지도에서 75개 발견

키워드 검색:  39%|███▊      | 12/31 [01:44<02:41,  8.48s/키워드]

   네이버 지도에서 75개 발견

키워드 검색:  42%|████▏     | 13/31 [01:53<02:34,  8.56s/키워드]

   네이버 지도에서 75개 발견

키워드 검색:  45%|████▌     | 14/31 [02:02<02:26,  8.61s/키워드]

   네이버 지도에서 75개 발견

키워드 검색:  48%|████▊     | 15/31 [02:11<02:19,  8.74s/키워드]

   네이버 지도에서 75개 발견

키워드 검색:  52%|█████▏    | 16/31 [02:18<02:04,  8.27s/키워드]

   네이버 지도에서 75개 발견

키워드 검색:  55%|█████▍    | 17/31 [02:27<01:56,  8.32s/키워드]

   네이버 지도에서 75개 발견

키워드 검색:  58%|█████▊    | 18/31 [02:34<01:44,  8.06s/키워드]

   네이버 지도에서 75개 발견

키워드 검색:  61%|██████▏   | 19/31 [02:42<01:35,  8.00s/키워드]

   네이버 지도에서 75개 발견

키워드 검색:  65%|██████▍   | 20/31 [02:50<01:28,  8.06s/키워드]

   네이버 지도에서 75개 발견

키워드 검색:  68%|██████▊   | 21/31 [02:57<01:17,  7.71s/키워드]

   네이버 지도에서 75개 발견

키워드 검색:  71%|███████   | 22/31 [03:05<01:11,  7.91s/키워드]

   네이버 지도에서 75개 발견

키워드 검색:  74%|███████▍  | 23/31 [03:14<01:05,  8.16s/키워드]

   네이버 지도에서 75개 발견

키워드 검색:  77%|███████▋  | 24/31 [03:21<00:55,  7.88s/키워드]

   네이버 지도에서 75개 발견

키워드 검색:  81%|████████  | 25/31 [03:31<00:50,  8.49s/키워드]

   네이버 지도에서 75개 발견

키워드 검색:  84%|████████▍ | 26/31 [03:40<00:42,  8.41s/키워드]

   네이버 지도에서 75개 발견

키워드 검색:  87%|████████▋ | 27/31 [03:47<00:31,  7.99s/키워드]

   네이버 지도에서 75개 발견

키워드 검색:  90%|█████████ | 28/31 [03:55<00:24,  8.11s/키워드]

   네이버 지도에서 75개 발견

키워드 검색:  94%|█████████▎| 29/31 [04:04<00:16,  8.34s/키워드]

   네이버 지도에서 75개 발견

키워드 검색:  97%|█████████▋| 30/31 [04:11<00:08,  8.03s/키워드]

   네이버 지도에서 75개 발견

키워드 검색: 100%|██████████| 31/31 [04:20<00:00,  8.40s/키워드]

   ✅ 620개 장소 수집 완료

📌 2단계: 상세 정보 수집

상세 정보 수집:  96%|█████████▌| 595/620 [1:42:54<07:23, 17.73s/장소, 현재=나루터]

   ⚠️ 홈 탭 오류 (1600878781): Timeout 30000ms exceeded.

상세 정보 수집: 100%|██████████| 620/620 [1:47:21<00:00, 10.39s/장소, 현재=리버브제주]

💾 중간 저장: ../../data/naver_places_20251129_221519.json

✅ 맛집/카페 크롤링 완료! 총 620개 수집
📍 위경도 있는 장소: 0개 (0.0%)

In [ ]:
# 💾 맛집/카페 데이터 PostgreSQL 적재
# 기존 데이터는 naver_id 기준으로 업데이트됩니다.

engine = create_tables()
load_to_postgres(food_cafe_data, engine)

# 적재 결과 확인
with engine.connect() as conn:
    result = conn.execute(text("SELECT COUNT(*) FROM places WHERE lat IS NOT NULL"))
    with_coords = result.fetchone()[0]
    
    result = conn.execute(text("SELECT COUNT(*) FROM places"))
    total = result.fetchone()[0]
    
    print(f"\n📊 PostgreSQL 적재 결과:")
    print(f"   총 장소: {total}개")
    print(f"   위경도 있는 장소: {with_coords}개 ({with_coords/total*100:.1f}%)")

📦 DB: localhost:5433/jeju_travel
✅ place_type 컬럼 추가 완료!

✅ 관광 데이터용 크롤링 함수 정의 완료!

🏞️ 관광 키워드: 104개
   - 자연: 22개
   - 문화: 17개
   - 해변: 17개
   - 액티비티: 24개
   - 숙박: 18개
⏱️ 예상 시간: 약 17분 (1단계) + 상세정보 수집

📌 1단계: 관광 데이터 검색

키워드 검색:   0%|          | 0/104 [00:00<?, ?키워드/s]

   네이버 지도에서 75개 발견

키워드 검색:   1%|          | 1/104 [00:12<21:31, 12.54s/키워드]

   네이버 지도에서 75개 발견

키워드 검색:   2%|▏         | 2/104 [00:24<21:12, 12.47s/키워드]

   네이버 지도에서 75개 발견

키워드 검색:   3%|▎         | 3/104 [00:37<20:50, 12.38s/키워드]

   네이버 지도에서 12개 발견

키워드 검색:   4%|▍         | 4/104 [00:48<20:07, 12.07s/키워드]

   네이버 지도에서 75개 발견

키워드 검색:   5%|▍         | 5/104 [01:02<20:43, 12.56s/키워드]

   네이버 지도에서 75개 발견

키워드 검색:   6%|▌         | 6/104 [01:15<21:09, 12.95s/키워드]

   네이버 지도에서 75개 발견

키워드 검색:   7%|▋         | 7/104 [01:29<21:24, 13.24s/키워드]

KeyboardInterrupt:

❌ 검색 실패 (제주 폭포): Page.evaluate: Connection closed while reading from the driver

키워드 검색:   8%|▊         | 8/104 [01:37<18:06, 11.32s/키워드]

❌ 검색 실패 (제주 한라산): Page.goto: Connection closed while reading from the driver

키워드 검색:   9%|▊         | 9/104 [01:39<13:22,  8.44s/키워드]

❌ 검색 실패 (제주 곶자왈): Page.goto: Connection closed while reading from the driver

키워드 검색:  10%|▉         | 10/104 [01:41<10:23,  6.64s/키워드]

❌ 검색 실패 (제주 올레길): Page.goto: Connection closed while reading from the driver

키워드 검색:  11%|█         | 11/104 [01:43<08:05,  5.23s/키워드]

❌ 검색 실패 (제주 돌하르방): Page.goto: Connection closed while reading from the driver

키워드 검색:  12%|█▏        | 12/104 [01:46<06:43,  4.39s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 용두암): Page.goto: Connection closed while reading from the driver

키워드 검색:  12%|█▎        | 13/104 [01:48<05:35,  3.69s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 산방산): Page.goto: Connection closed while reading from the driver

키워드 검색:  13%|█▎        | 14/104 [01:52<05:35,  3.73s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 천지연폭포): Page.goto: Connection closed while reading from the driver

키워드 검색:  14%|█▍        | 15/104 [01:55<05:25,  3.65s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 정방폭포): Page.goto: Connection closed while reading from the driver

키워드 검색:  15%|█▌        | 16/104 [01:58<04:54,  3.34s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 천제연폭포): Page.goto: Connection closed while reading from the driver

키워드 검색:  16%|█▋        | 17/104 [02:01<04:45,  3.28s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 성산일출봉): Page.goto: Connection closed while reading from the driver

키워드 검색:  17%|█▋        | 18/104 [02:03<04:14,  2.96s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 만장굴): Page.goto: Connection closed while reading from the driver

키워드 검색:  18%|█▊        | 19/104 [02:06<04:21,  3.08s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 용천동굴): Page.goto: Connection closed while reading from the driver

키워드 검색:  19%|█▉        | 20/104 [02:09<04:14,  3.03s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 비자림): Page.goto: Connection closed while reading from the driver

키워드 검색:  20%|██        | 21/104 [02:12<04:08,  2.99s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 사려니숲길): Page.goto: Connection closed while reading from the driver

키워드 검색:  21%|██        | 22/104 [02:16<04:29,  3.29s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 에코랜드): Page.goto: Connection closed while reading from the driver

키워드 검색:  22%|██▏       | 23/104 [02:19<04:23,  3.26s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 박물관): Page.goto: Connection closed while reading from the driver

키워드 검색:  23%|██▎       | 24/104 [02:23<04:16,  3.21s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 미술관): Page.goto: Connection closed while reading from the driver

키워드 검색:  24%|██▍       | 25/104 [02:25<03:48,  2.89s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 전시회): Page.goto: Connection closed while reading from the driver

키워드 검색:  25%|██▌       | 26/104 [02:28<03:49,  2.94s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 역사): Page.goto: Connection closed while reading from the driver

키워드 검색:  26%|██▌       | 27/104 [02:32<04:08,  3.22s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 문화유적): Page.goto: Connection closed while reading from the driver

키워드 검색:  27%|██▋       | 28/104 [02:34<03:48,  3.01s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 민속촌): Page.goto: Connection closed while reading from the driver

키워드 검색:  28%|██▊       | 29/104 [02:36<03:28,  2.78s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 제주목관아): Page.goto: Connection closed while reading from the driver

키워드 검색:  29%|██▉       | 30/104 [02:40<03:47,  3.07s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 항일기념관): Page.goto: Connection closed while reading from the driver

키워드 검색:  30%|██▉       | 31/104 [02:44<03:54,  3.21s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 테마파크): Page.goto: Connection closed while reading from the driver

키워드 검색:  31%|███       | 32/104 [02:47<03:46,  3.15s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 아쿠아리움): Page.goto: Connection closed while reading from the driver

키워드 검색:  32%|███▏      | 33/104 [02:50<03:40,  3.11s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 플라네타리움): Page.goto: Connection closed while reading from the driver

키워드 검색:  33%|███▎      | 34/104 [02:53<03:38,  3.12s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 세계자연유산): Page.goto: Connection closed while reading from the driver

키워드 검색:  34%|███▎      | 35/104 [02:55<03:15,  2.83s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 유네스코): Page.goto: Connection closed while reading from the driver

키워드 검색:  35%|███▍      | 36/104 [02:58<03:18,  2.92s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 체험): Page.goto: Connection closed while reading from the driver

키워드 검색:  36%|███▌      | 37/104 [03:00<02:59,  2.68s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 도예체험): Page.goto: Connection closed while reading from the driver

키워드 검색:  37%|███▋      | 38/104 [03:03<02:52,  2.61s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 공방): Page.goto: Connection closed while reading from the driver

키워드 검색:  38%|███▊      | 39/104 [03:05<02:52,  2.66s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 전통시장): Page.goto: Connection closed while reading from the driver

키워드 검색:  38%|███▊      | 40/104 [03:08<02:54,  2.73s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 오일장): Page.goto: Connection closed while reading from the driver

키워드 검색:  39%|███▉      | 41/104 [03:11<02:50,  2.71s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 해변): Page.goto: Connection closed while reading from the driver

키워드 검색:  40%|████      | 42/104 [03:14<02:45,  2.68s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 해수욕장): Page.goto: Connection closed while reading from the driver

키워드 검색:  41%|████▏     | 43/104 [03:18<03:05,  3.04s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 바다): Page.goto: Connection closed while reading from the driver

키워드 검색:  42%|████▏     | 44/104 [03:20<02:44,  2.74s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 협재해수욕장): Page.goto: Connection closed while reading from the driver

키워드 검색:  43%|████▎     | 45/104 [03:23<02:46,  2.83s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 함덕해수욕장): Page.goto: Connection closed while reading from the driver

키워드 검색:  44%|████▍     | 46/104 [03:26<02:46,  2.87s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 이호테우해변): Page.goto: Connection closed while reading from the driver

키워드 검색:  45%|████▌     | 47/104 [03:29<02:59,  3.15s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 월정리해변): Page.goto: Connection closed while reading from the driver

키워드 검색:  46%|████▌     | 48/104 [03:32<02:44,  2.93s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 김녕해수욕장): Page.goto: Connection closed while reading from the driver

키워드 검색:  47%|████▋     | 49/104 [03:35<02:51,  3.12s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 표선해수욕장): Page.goto: Connection closed while reading from the driver

키워드 검색:  48%|████▊     | 50/104 [03:39<02:56,  3.27s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 중문해수욕장): Page.goto: Connection closed while reading from the driver

키워드 검색:  49%|████▉     | 51/104 [03:42<02:48,  3.19s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 금능해수욕장): Page.goto: Connection closed while reading from the driver

키워드 검색:  50%|█████     | 52/104 [03:45<02:50,  3.28s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 우도 해변): Page.goto: Connection closed while reading from the driver

키워드 검색:  51%|█████     | 53/104 [03:48<02:29,  2.94s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 비양도): Page.goto: Connection closed while reading from the driver

키워드 검색:  52%|█████▏    | 54/104 [03:51<02:34,  3.09s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 스노클링): Page.goto: Connection closed while reading from the driver

키워드 검색:  53%|█████▎    | 55/104 [03:53<02:21,  2.88s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 해안도로): Page.goto: Connection closed while reading from the driver

키워드 검색:  54%|█████▍    | 56/104 [03:57<02:30,  3.14s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 포구): Page.goto: Connection closed while reading from the driver

키워드 검색:  55%|█████▍    | 57/104 [04:01<02:37,  3.36s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 항구): Page.goto: Connection closed while reading from the driver

키워드 검색:  56%|█████▌    | 58/104 [04:05<02:39,  3.46s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 일출 명소): Page.goto: Connection closed while reading from the driver

키워드 검색:  57%|█████▋    | 59/104 [04:07<02:20,  3.12s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 액티비티): Page.goto: Connection closed while reading from the driver

키워드 검색:  58%|█████▊    | 60/104 [04:11<02:22,  3.24s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 레저): Page.goto: Connection closed while reading from the driver

키워드 검색:  59%|█████▊    | 61/104 [04:13<02:14,  3.13s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 어드벤처): Page.goto: Connection closed while reading from the driver

키워드 검색:  60%|█████▉    | 62/104 [04:16<02:01,  2.88s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 스쿠버다이빙): Page.goto: Connection closed while reading from the driver

키워드 검색:  61%|██████    | 63/104 [04:20<02:09,  3.15s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 다이빙): Page.goto: Connection closed while reading from the driver

키워드 검색:  62%|██████▏   | 64/104 [04:22<01:55,  2.89s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 서핑): Page.goto: Connection closed while reading from the driver

키워드 검색:  62%|██████▎   | 65/104 [04:25<01:58,  3.05s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 카약): Page.goto: Connection closed while reading from the driver

키워드 검색:  63%|██████▎   | 66/104 [04:28<01:54,  3.01s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 요트): Page.goto: Connection closed while reading from the driver

키워드 검색:  64%|██████▍   | 67/104 [04:31<01:49,  2.95s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 낚시): Page.goto: Connection closed while reading from the driver

키워드 검색:  65%|██████▌   | 68/104 [04:34<01:50,  3.07s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 승마): Page.goto: Connection closed while reading from the driver

키워드 검색:  66%|██████▋   | 69/104 [04:37<01:38,  2.81s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 승마체험): Page.goto: Connection closed while reading from the driver

키워드 검색:  67%|██████▋   | 70/104 [04:39<01:34,  2.79s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 ATV): Page.goto: Connection closed while reading from the driver

키워드 검색:  68%|██████▊   | 71/104 [04:41<01:26,  2.62s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 패러글라이딩): Page.goto: Connection closed while reading from the driver

키워드 검색:  69%|██████▉   | 72/104 [04:45<01:36,  3.00s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 짚라인): Page.goto: Connection closed while reading from the driver

키워드 검색:  70%|███████   | 73/104 [04:48<01:32,  3.00s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 레일바이크): Page.goto: Connection closed while reading from the driver

키워드 검색:  71%|███████   | 74/104 [04:51<01:28,  2.94s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 골프): Page.goto: Connection closed while reading from the driver

키워드 검색:  72%|███████▏  | 75/104 [04:54<01:26,  2.98s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 골프장): Page.goto: Connection closed while reading from the driver

키워드 검색:  73%|███████▎  | 76/104 [04:57<01:19,  2.84s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 수상레저): Page.goto: Connection closed while reading from the driver

키워드 검색:  74%|███████▍  | 77/104 [05:00<01:16,  2.84s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 제트스키): Page.goto: Connection closed while reading from the driver

키워드 검색:  75%|███████▌  | 78/104 [05:03<01:14,  2.87s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 바나나보트): Page.goto: Connection closed while reading from the driver

키워드 검색:  76%|███████▌  | 79/104 [05:06<01:14,  2.98s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 MTB): Page.goto: Connection closed while reading from the driver

키워드 검색:  77%|███████▋  | 80/104 [05:09<01:11,  2.98s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 자전거): Page.goto: Connection closed while reading from the driver

키워드 검색:  78%|███████▊  | 81/104 [05:11<01:02,  2.71s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 렌트카): Page.goto: Connection closed while reading from the driver

키워드 검색:  79%|███████▉  | 82/104 [05:14<01:00,  2.76s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 보트투어): Page.goto: Connection closed while reading from the driver

키워드 검색:  80%|███████▉  | 83/104 [05:16<00:56,  2.68s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 요트투어): Page.goto: Connection closed while reading from the driver

키워드 검색:  81%|████████  | 84/104 [05:19<00:55,  2.77s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 선상낚시): Page.goto: Connection closed while reading from the driver

키워드 검색:  82%|████████▏ | 85/104 [05:22<00:54,  2.87s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 호텔): Page.goto: Connection closed while reading from the driver

키워드 검색:  83%|████████▎ | 86/104 [05:26<00:57,  3.17s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 5성호텔): Page.goto: Connection closed while reading from the driver

키워드 검색:  84%|████████▎ | 87/104 [05:29<00:54,  3.19s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 특급호텔): Page.goto: Connection closed while reading from the driver

키워드 검색:  85%|████████▍ | 88/104 [05:32<00:46,  2.91s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (서귀포 호텔): Page.goto: Connection closed while reading from the driver

키워드 검색:  86%|████████▌ | 89/104 [05:35<00:45,  3.02s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (중문 호텔): Page.goto: Connection closed while reading from the driver

키워드 검색:  87%|████████▋ | 90/104 [05:37<00:39,  2.81s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (애월 호텔): Page.goto: Connection closed while reading from the driver

키워드 검색:  88%|████████▊ | 91/104 [05:40<00:35,  2.74s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 리조트): Page.goto: Connection closed while reading from the driver

키워드 검색:  88%|████████▊ | 92/104 [05:44<00:36,  3.06s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (중문 리조트): Page.goto: Connection closed while reading from the driver

키워드 검색:  89%|████████▉ | 93/104 [05:46<00:30,  2.76s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 풀빌라): Page.goto: Connection closed while reading from the driver

키워드 검색:  90%|█████████ | 94/104 [05:49<00:27,  2.78s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 펜션): Page.goto: Connection closed while reading from the driver

키워드 검색:  91%|█████████▏| 95/104 [05:52<00:26,  2.94s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (서귀포 펜션): Page.goto: Connection closed while reading from the driver

키워드 검색:  92%|█████████▏| 96/104 [05:54<00:22,  2.86s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (애월 펜션): Page.goto: Connection closed while reading from the driver

키워드 검색:  93%|█████████▎| 97/104 [05:57<00:19,  2.74s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (함덕 펜션): Page.goto: Connection closed while reading from the driver

키워드 검색:  94%|█████████▍| 98/104 [06:00<00:17,  2.89s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 게스트하우스): Page.goto: Connection closed while reading from the driver

키워드 검색:  95%|█████████▌| 99/104 [06:03<00:13,  2.79s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 민박): Page.goto: Connection closed while reading from the driver

키워드 검색:  96%|█████████▌| 100/104 [06:06<00:11,  2.83s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 오션뷰 숙소): Page.goto: Connection closed while reading from the driver

키워드 검색:  97%|█████████▋| 101/104 [06:08<00:07,  2.66s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 독채 펜션): Page.goto: Connection closed while reading from the driver

키워드 검색:  98%|█████████▊| 102/104 [06:10<00:05,  2.59s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 가족 숙소): Page.goto: Connection closed while reading from the driver

키워드 검색:  99%|█████████▉| 103/104 [06:14<00:03,  3.01s/키워드]pipe closed by peer or os.write(pipe, data) raised exception.

❌ 검색 실패 (제주 커플 숙소): Page.goto: Connection closed while reading from the driver

키워드 검색: 100%|██████████| 104/104 [06:18<00:00,  3.64s/키워드]

   ✅ 149개 장소 수집 완료

📌 2단계: 상세 정보 수집

상세 정보 수집:   0%|          | 0/149 [00:00<?, ?장소/s]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (33359625): Page.goto: Connection closed while reading from the driver

상세 정보 수집:   1%|          | 1/149 [00:02<05:31,  2.24s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (11607760): Page.goto: Connection closed while reading from the driver

상세 정보 수집:   1%|▏         | 2/149 [00:05<07:04,  2.89s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (17029023): Page.goto: Connection closed while reading from the driver

상세 정보 수집:   2%|▏         | 3/149 [00:09<08:14,  3.39s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1104457165): Page.goto: Connection closed while reading from the driver

상세 정보 수집:   3%|▎         | 4/149 [00:13<08:34,  3.55s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (17088184): Page.goto: Connection closed while reading from the driver

상세 정보 수집:   3%|▎         | 5/149 [00:16<08:08,  3.39s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (13529824): Page.goto: Connection closed while reading from the driver

상세 정보 수집:   4%|▍         | 6/149 [00:18<07:17,  3.06s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (17031585): Page.goto: Connection closed while reading from the driver

상세 정보 수집:   5%|▍         | 7/149 [00:22<07:35,  3.21s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (20378654): Page.goto: Connection closed while reading from the driver

상세 정보 수집:   5%|▌         | 8/149 [00:26<08:01,  3.41s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (17020866): Page.goto: Connection closed while reading from the driver

상세 정보 수집:   6%|▌         | 9/149 [00:29<08:07,  3.49s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1882939263): Page.goto: Connection closed while reading from the driver

상세 정보 수집:   7%|▋         | 10/149 [00:32<07:09,  3.09s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (17075242): Page.goto: Connection closed while reading from the driver

상세 정보 수집:   7%|▋         | 11/149 [00:34<06:20,  2.76s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (17082282): Page.goto: Connection closed while reading from the driver

상세 정보 수집:   8%|▊         | 12/149 [00:37<07:02,  3.08s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (17088805): Page.goto: Connection closed while reading from the driver

상세 정보 수집:   9%|▊         | 13/149 [00:41<07:02,  3.11s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (31093439): Page.goto: Connection closed while reading from the driver

상세 정보 수집:   9%|▉         | 14/149 [00:44<07:31,  3.34s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (13481082): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  10%|█         | 15/149 [00:47<07:01,  3.15s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (13165795): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  11%|█         | 16/149 [00:49<06:17,  2.84s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (17071747): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  11%|█▏        | 17/149 [00:53<06:58,  3.17s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (21370013): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  12%|█▏        | 18/149 [00:55<06:17,  2.88s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1146564530): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  13%|█▎        | 19/149 [00:58<05:58,  2.76s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1024484886): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  13%|█▎        | 20/149 [01:01<05:55,  2.75s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1987327374): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  14%|█▍        | 21/149 [01:04<06:22,  2.99s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (11885803): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  15%|█▍        | 22/149 [01:08<06:35,  3.11s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (31825951): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  15%|█▌        | 23/149 [01:10<06:01,  2.87s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (17030080): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  16%|█▌        | 24/149 [01:14<06:31,  3.13s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (17029964): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  17%|█▋        | 25/149 [01:16<06:09,  2.98s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1876553757): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  17%|█▋        | 26/149 [01:20<06:41,  3.27s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (16998275): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  18%|█▊        | 27/149 [01:24<06:46,  3.34s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1275868092): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  19%|█▉        | 28/149 [01:28<07:03,  3.50s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1499802944): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  19%|█▉        | 29/149 [01:31<06:47,  3.40s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (17011304): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  20%|██        | 30/149 [01:34<06:42,  3.38s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (13481066): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  21%|██        | 31/149 [01:38<06:51,  3.49s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (31390248): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  21%|██▏       | 32/149 [01:41<06:45,  3.46s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (31390250): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  22%|██▏       | 33/149 [01:45<06:55,  3.58s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1670694152): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  23%|██▎       | 34/149 [01:48<06:16,  3.27s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1126179674): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  23%|██▎       | 35/149 [01:51<06:14,  3.29s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1983568149): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  24%|██▍       | 36/149 [01:54<05:49,  3.10s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (31390247): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  25%|██▍       | 37/149 [01:58<06:16,  3.36s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1390440179): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  26%|██▌       | 38/149 [02:00<05:31,  2.98s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (32566228): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  26%|██▌       | 39/149 [02:03<05:46,  3.15s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1609314160): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  27%|██▋       | 40/149 [02:07<06:00,  3.31s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (97720184): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  28%|██▊       | 41/149 [02:09<05:27,  3.03s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1716040619): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  28%|██▊       | 42/149 [02:12<05:04,  2.85s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1838048325): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  29%|██▉       | 43/149 [02:15<05:04,  2.87s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (31390245): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  30%|██▉       | 44/149 [02:17<04:55,  2.82s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1281846496): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  30%|███       | 45/149 [02:19<04:28,  2.58s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (31390249): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  31%|███       | 46/149 [02:21<04:11,  2.44s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1899143017): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  32%|███▏      | 47/149 [02:24<03:56,  2.32s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (2048021103): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  32%|███▏      | 48/149 [02:26<04:00,  2.38s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (32566226): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  33%|███▎      | 49/149 [02:30<04:36,  2.77s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1560878774): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  34%|███▎      | 50/149 [02:32<04:13,  2.56s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1775314281): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  34%|███▍      | 51/149 [02:34<03:57,  2.43s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (13425146): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  35%|███▍      | 52/149 [02:36<03:56,  2.44s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (17037128): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  36%|███▌      | 53/149 [02:40<04:37,  2.90s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1479682717): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  36%|███▌      | 54/149 [02:44<04:43,  2.99s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1604280902): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  37%|███▋      | 55/149 [02:47<04:43,  3.01s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1355982290): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  38%|███▊      | 56/149 [02:49<04:32,  2.93s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1428549647): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  38%|███▊      | 57/149 [02:53<04:39,  3.04s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (31390251): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  39%|███▉      | 58/149 [02:55<04:25,  2.92s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (457356266): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  40%|███▉      | 59/149 [02:57<03:59,  2.66s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1012239078): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  40%|████      | 60/149 [03:00<03:57,  2.67s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (699852173): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  41%|████      | 61/149 [03:04<04:21,  2.97s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1442480138): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  42%|████▏     | 62/149 [03:07<04:26,  3.06s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1143874474): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  42%|████▏     | 63/149 [03:11<04:47,  3.34s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (37548919): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  43%|████▎     | 64/149 [03:13<04:23,  3.10s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1163121661): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  44%|████▎     | 65/149 [03:17<04:18,  3.08s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1059053793): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  44%|████▍     | 66/149 [03:20<04:19,  3.13s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (38414793): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  45%|████▍     | 67/149 [03:23<04:09,  3.04s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1026880844): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  46%|████▌     | 68/149 [03:25<04:01,  2.99s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1170899998): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  46%|████▋     | 69/149 [03:28<03:42,  2.78s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1952074874): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  47%|████▋     | 70/149 [03:31<03:47,  2.89s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1421417848): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  48%|████▊     | 71/149 [03:34<03:51,  2.96s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1923332221): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  48%|████▊     | 72/149 [03:38<04:03,  3.16s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1216529782): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  49%|████▉     | 73/149 [03:40<03:39,  2.89s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (112862112): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  50%|████▉     | 74/149 [03:42<03:19,  2.66s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1690179903): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  50%|█████     | 75/149 [03:45<03:15,  2.65s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1999227432): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  51%|█████     | 76/149 [03:47<03:08,  2.58s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1720957421): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  52%|█████▏    | 77/149 [03:50<03:13,  2.69s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (38704284): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  52%|█████▏    | 78/149 [03:53<03:14,  2.75s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (13460691): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  53%|█████▎    | 79/149 [03:55<03:05,  2.65s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (13481079): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  54%|█████▎    | 80/149 [03:59<03:23,  2.96s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (19654321): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  54%|█████▍    | 81/149 [04:01<03:03,  2.70s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (13481075): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  55%|█████▌    | 82/149 [04:04<03:02,  2.72s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1718891281): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  56%|█████▌    | 83/149 [04:08<03:22,  3.07s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1692515094): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  56%|█████▋    | 84/149 [04:11<03:21,  3.09s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1167656839): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  57%|█████▋    | 85/149 [04:14<03:20,  3.13s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1203413489): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  58%|█████▊    | 86/149 [04:17<03:17,  3.13s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1385305363): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  58%|█████▊    | 87/149 [04:20<03:12,  3.11s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (38511154): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  59%|█████▉    | 88/149 [04:24<03:13,  3.17s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (31317199): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  60%|█████▉    | 89/149 [04:27<03:21,  3.37s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1750524890): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  60%|██████    | 90/149 [04:30<02:58,  3.03s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (2146442719): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  61%|██████    | 91/149 [04:32<02:43,  2.81s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1971382473): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  62%|██████▏   | 92/149 [04:35<02:39,  2.79s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (21393600): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  62%|██████▏   | 93/149 [04:38<02:49,  3.02s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (31317189): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  63%|██████▎   | 94/149 [04:41<02:40,  2.93s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (31317194): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  64%|██████▍   | 95/149 [04:45<02:50,  3.15s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1706647582): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  64%|██████▍   | 96/149 [04:47<02:38,  2.99s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1227411306): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  65%|██████▌   | 97/149 [04:51<02:44,  3.17s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (2144420396): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  66%|██████▌   | 98/149 [04:53<02:29,  2.94s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (31317173): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  66%|██████▋   | 99/149 [04:56<02:26,  2.94s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (31317201): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  67%|██████▋   | 100/149 [04:59<02:22,  2.92s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (34186887): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  68%|██████▊   | 101/149 [05:03<02:28,  3.09s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (12047800): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  68%|██████▊   | 102/149 [05:05<02:22,  3.03s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (13491455): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  69%|██████▉   | 103/149 [05:08<02:09,  2.81s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (13490878): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  70%|██████▉   | 104/149 [05:10<01:57,  2.62s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (13072135): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  70%|███████   | 105/149 [05:12<01:50,  2.52s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (13350575): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  71%|███████   | 106/149 [05:15<01:50,  2.57s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1934268430): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  72%|███████▏  | 107/149 [05:17<01:46,  2.53s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (17063361): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  72%|███████▏  | 108/149 [05:21<01:58,  2.90s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (37232778): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  73%|███████▎  | 109/149 [05:24<01:51,  2.80s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (13491801): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  74%|███████▍  | 110/149 [05:27<01:59,  3.07s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (13542738): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  74%|███████▍  | 111/149 [05:30<01:54,  3.01s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (19658870): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  75%|███████▌  | 112/149 [05:33<01:47,  2.90s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (13481038): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  76%|███████▌  | 113/149 [05:36<01:51,  3.10s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (20034615): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  77%|███████▋  | 114/149 [05:39<01:40,  2.87s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (13481080): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  77%|███████▋  | 115/149 [05:41<01:35,  2.80s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (20027766): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  78%|███████▊  | 116/149 [05:45<01:39,  3.01s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1053164031): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  79%|███████▊  | 117/149 [05:48<01:40,  3.13s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1464343555): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  79%|███████▉  | 118/149 [05:51<01:29,  2.88s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1539131369): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  80%|███████▉  | 119/149 [05:53<01:22,  2.74s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1196006105): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  81%|████████  | 120/149 [05:55<01:14,  2.56s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (11491209): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  81%|████████  | 121/149 [05:58<01:11,  2.57s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (17099516): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  82%|████████▏ | 122/149 [06:00<01:06,  2.48s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (13481072): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  83%|████████▎ | 123/149 [06:04<01:14,  2.87s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1372279326): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  83%|████████▎ | 124/149 [06:08<01:18,  3.15s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1154910382): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  84%|████████▍ | 125/149 [06:10<01:11,  2.97s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (11491146): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  85%|████████▍ | 126/149 [06:13<01:09,  3.00s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (13491576): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  85%|████████▌ | 127/149 [06:16<01:07,  3.07s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1253199487): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  86%|████████▌ | 128/149 [06:19<00:57,  2.76s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (13583371): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  87%|████████▋ | 129/149 [06:22<00:59,  2.99s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1313952084): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  87%|████████▋ | 130/149 [06:25<00:57,  3.03s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (13481272): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  88%|████████▊ | 131/149 [06:28<00:56,  3.13s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1344046630): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  89%|████████▊ | 132/149 [06:32<00:54,  3.22s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1739801034): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  89%|████████▉ | 133/149 [06:35<00:51,  3.19s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1411950047): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  90%|████████▉ | 134/149 [06:39<00:51,  3.43s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (2142528182): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  91%|█████████ | 135/149 [06:43<00:49,  3.51s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (31206936): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  91%|█████████▏| 136/149 [06:47<00:46,  3.58s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1656319334): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  92%|█████████▏| 137/149 [06:50<00:41,  3.48s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1520156554): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  93%|█████████▎| 138/149 [06:52<00:34,  3.18s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (17082520): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  93%|█████████▎| 139/149 [06:54<00:28,  2.83s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (919754842): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  94%|█████████▍| 140/149 [06:58<00:27,  3.01s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (1603175831): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  95%|█████████▍| 141/149 [07:00<00:22,  2.80s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (17082367): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  95%|█████████▌| 142/149 [07:02<00:18,  2.58s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (37783972): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  96%|█████████▌| 143/149 [07:04<00:14,  2.49s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (37783977): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  97%|█████████▋| 144/149 [07:07<00:13,  2.68s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (37784020): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  97%|█████████▋| 145/149 [07:10<00:10,  2.70s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (37783962): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  98%|█████████▊| 146/149 [07:14<00:08,  2.92s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (37784016): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  99%|█████████▊| 147/149 [07:16<00:05,  2.85s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (37783938): Page.goto: Connection closed while reading from the driver

상세 정보 수집:  99%|█████████▉| 148/149 [07:20<00:03,  3.03s/장소]pipe closed by peer or os.write(pipe, data) raised exception.

   ⚠️ 상세 정보 수집 오류 (38300991): Page.goto: Connection closed while reading from the driver

상세 정보 수집: 100%|██████████| 149/149 [07:23<00:00,  2.98s/장소]
pipe closed by peer or os.write(pipe, data) raised exception.

💾 중간 저장: ../../data/naver_tourism_20251204_040132.json

## 6. 데이터 정제 및 CSV 저장

## 7. PostgreSQL 적재

In [ ]:
import os
from sqlalchemy import create_engine, text

# DB 연결 정보
DB_CONFIG = {
    "host": os.getenv("DB_HOST", "localhost"),
    "port": os.getenv("DB_PORT", "5433"),
    "database": os.getenv("DB_NAME", "jeju_travel"),
    "user": os.getenv("DB_USER", "jeju_user"),
    "password": os.getenv("DB_PASSWORD", "jeju_password"),
}

# 테이블 생성 SQL (places + menus 분리)
CREATE_TABLE_SQL = """
-- 장소 테이블
CREATE TABLE IF NOT EXISTS places (
    id SERIAL PRIMARY KEY,
    naver_id VARCHAR(100) UNIQUE,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(100),
    address TEXT,
    phone VARCHAR(20),
    
    -- 평점/리뷰
    rating DECIMAL(2, 1),
    review_count INTEGER DEFAULT 0,
    
    -- 가격 정보
    min_price INTEGER,
    max_price INTEGER,
    price_range VARCHAR(20),  -- 저렴/보통/비쌈/고급
    
    -- 편의시설
    parking BOOLEAN DEFAULT FALSE,
    kid_friendly BOOLEAN DEFAULT FALSE,
    wheelchair BOOLEAN DEFAULT FALSE,
    pet_friendly BOOLEAN DEFAULT FALSE,
    reservation BOOLEAN DEFAULT FALSE,
    wifi BOOLEAN DEFAULT FALSE,
    
    -- 기타
    business_hours TEXT,
    url TEXT,
    created_at TIMESTAMP DEFAULT NOW()
);

-- 메뉴 테이블 (1:N)
CREATE TABLE IF NOT EXISTS menus (
    id SERIAL PRIMARY KEY,
    place_id INTEGER REFERENCES places(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    price INTEGER,
    category VARCHAR(50)  -- 메인/단품/음료/사이드
);

-- 인덱스
CREATE INDEX IF NOT EXISTS idx_places_category ON places(category);
CREATE INDEX IF NOT EXISTS idx_places_rating ON places(rating);
CREATE INDEX IF NOT EXISTS idx_places_review_count ON places(review_count);
CREATE INDEX IF NOT EXISTS idx_places_min_price ON places(min_price);
CREATE INDEX IF NOT EXISTS idx_places_parking ON places(parking);
CREATE INDEX IF NOT EXISTS idx_places_kid_friendly ON places(kid_friendly);
CREATE INDEX IF NOT EXISTS idx_menus_place_id ON menus(place_id);
CREATE INDEX IF NOT EXISTS idx_menus_price ON menus(price);
"""

def create_tables():
    """테이블 생성 (places + menus)"""
    conn_str = f"postgresql://{DB_CONFIG['user']}:{DB_CONFIG['password']}@{DB_CONFIG['host']}:{DB_CONFIG['port']}/{DB_CONFIG['database']}"
    engine = create_engine(conn_str)
    
    with engine.connect() as conn:
        conn.execute(text(CREATE_TABLE_SQL))
        conn.commit()
    
    print("✅ places, menus 테이블 생성 완료!")
    return engine


print(f"📦 DB: {DB_CONFIG['host']}:{DB_CONFIG['port']}/{DB_CONFIG['database']}")

📦 DB: localhost:5433/jeju_travel

In [13]:
# 테이블 생성 (Docker가 실행 중이어야 함)
engine = create_tables()

✅ places, menus 테이블 생성 완료!

In [14]:
def load_to_postgres(data: List[Dict], engine):
    """데이터를 PostgreSQL에 적재 (places + menus)"""
    
    with engine.connect() as conn:
        for item in data:
            # 데이터 검증 및 정제
            rating = item.get("rating")
            if rating is not None and (rating > 5.0 or rating < 0):
                rating = None  # 잘못된 평점은 제거
            
            review_count = item.get("review_count", 0)
            if not isinstance(review_count, int):
                try:
                    review_count = int(review_count) if review_count else 0
                except:
                    review_count = 0
            # 1. places 테이블에 저장 (lat, lng 포함!)
            place_sql = text("""
                INSERT INTO places (
                    naver_id, name, category, address, phone,
                    rating, review_count, min_price, max_price, price_range,
                    parking, kid_friendly, wheelchair, pet_friendly, reservation, wifi,
                    business_hours, url, lat, lng
                ) VALUES (
                    :naver_id, :name, :category, :address, :phone,
                    :rating, :review_count, :min_price, :max_price, :price_range,
                    :parking, :kid_friendly, :wheelchair, :pet_friendly, :reservation, :wifi,
                    :business_hours, :url, :lat, :lng
                )
                ON CONFLICT (naver_id) DO UPDATE SET
                    rating = EXCLUDED.rating,
                    review_count = EXCLUDED.review_count,
                    min_price = EXCLUDED.min_price,
                    max_price = EXCLUDED.max_price,
                    lat = EXCLUDED.lat,
                    lng = EXCLUDED.lng
                RETURNING id
            """)
            
            result = conn.execute(place_sql, {
                "naver_id": item.get("naver_id"),
                "name": item.get("name"),
                "category": item.get("category"),
                "address": item.get("address"),
                "phone": item.get("phone", ""),
                "rating": rating,  # 검증된 값 사용
                "review_count": review_count,  # 검증된 값 사용
                "min_price": item.get("min_price"),
                "max_price": item.get("max_price"),
                "price_range": item.get("price_range", ""),
                "parking": item.get("parking", False),
                "kid_friendly": item.get("kid_friendly", False),
                "wheelchair": item.get("wheelchair", False),
                "pet_friendly": item.get("pet_friendly", False),
                "reservation": item.get("reservation", False),
                "wifi": item.get("wifi", False),
                "business_hours": item.get("business_hours", ""),
                "url": item.get("url", ""),
                "lat": item.get("lat"),  # 위도 추가!
                "lng": item.get("lng"),  # 경도 추가!
            })
            
            place_id = result.fetchone()[0]
            
            # 2. menus 테이블에 저장
            menus = item.get("menus", [])
            if menus and place_id:
                # 기존 메뉴 삭제
                conn.execute(text("DELETE FROM menus WHERE place_id = :place_id"), {"place_id": place_id})
                
                # 새 메뉴 저장
                for menu in menus:
                    menu_sql = text("""
                        INSERT INTO menus (place_id, name, price, category)
                        VALUES (:place_id, :name, :price, :category)
                    """)
                    conn.execute(menu_sql, {
                        "place_id": place_id,
                        "name": menu.get("name"),
                        "price": menu.get("price"),
                        "category": menu.get("category", ""),
                    })
        
        conn.commit()
    
    print(f"✅ {len(data)}개 장소 + 메뉴 적재 완료!")

In [19]:

# 데이터 적재 (테이블 생성 후 실행)
engine = create_tables()
load_to_postgres(food_cafe_data, engine)

✅ places, menus 테이블 생성 완료!
✅ 620개 장소 + 메뉴 적재 완료!

## 8. 다음 단계

1. ✅ 테스트 크롤링 실행 → 결과 확인
2. 셀렉터 수정 (네이버 DOM 변경 시)
3. 본 크롤링 실행
4. PostgreSQL 적재
5. SQL Agent 테스트

In [22]:
# 적재된 데이터 확인
import pandas as pd
from sqlalchemy import create_engine, text

# DB 연결
engine = create_engine("postgresql://jeju_user:jeju_password@localhost:5433/jeju_travel")

# 1. places 테이블 확인
print("=== places 테이블 ===")
with engine.connect() as conn:
    result = conn.execute(text("SELECT COUNT(*) FROM places"))
    count = result.fetchone()[0]
    print(f"총 {count}개 장소")
    
    # 샘플 데이터 조회
    df = pd.read_sql("SELECT * FROM places LIMIT 10", conn)
    display(df)

# 2. menus 테이블 확인
print("\n=== menus 테이블 ===")
with engine.connect() as conn:
    result = conn.execute(text("SELECT COUNT(*) FROM menus"))
    count = result.fetchone()[0]
    print(f"총 {count}개 메뉴")
    
    # 샘플 데이터 조회
    df = pd.read_sql("SELECT * FROM menus LIMIT 10", conn)
    display(df)

# 3. 통계 확인
print("\n=== 통계 ===")
with engine.connect() as conn:
    # 카테고리별 개수
    df = pd.read_sql("""
        SELECT category, COUNT(*) as cnt 
        FROM places 
        GROUP BY category 
        ORDER BY cnt DESC 
        LIMIT 10
    """, conn)
    print("카테고리별 장소 수:")
    display(df)
    
    # 평점 분포
    df = pd.read_sql("""
        SELECT 
            ROUND(rating, 0) as rating_group,
            COUNT(*) as cnt
        FROM places 
        WHERE rating IS NOT NULL
        GROUP BY rating_group
        ORDER BY rating_group
    """, conn)
    print("\n평점 분포:")
    display(df)

=== places 테이블 ===
총 608개 장소

,id,naver_id,name,category,address,phone,rating,review_count,min_price,max_price,...,wheelchair,pet_friendly,reservation,wifi,business_hours,url,created_at,region,lat,lng
0,1571,1284227366,노타메노 스키야키 제주공항점,샤브샤브,제주 제주시 무근성7길 17 1층,,NaN,684,2000,28000,...,False,True,True,False,영업 중\n21:00에 라스트오더\n21시 0분에 라스트오더,https://m.place.naver.com/restaurant/128422736...,2025-11-29 13:26:50.243901,제주시,33.514364,126.520182
1,1572,1976043123,동문시장 과일모찌 운화당,"카페,디저트",제주 제주시 동문로 6-4 1층 동문시장 과일모찌 운화당,,4.9,934,3500,25000,...,False,True,True,False,영업 종료\n내일 휴무\n내일 휴무,https://m.place.naver.com/restaurant/197604312...,2025-11-29 13:26:50.243901,제주시,33.512587,126.527142
2,1573,1435246450,은강횟집 제주공항본점,생선회,제주 제주시 연오로 8 1층 은강횟집,07-1375-4487,NaN,934,55000,150000,...,True,False,True,False,영업 중\n21:30에 라스트오더\n21시 30분에 라스트오더,https://m.place.naver.com/restaurant/143524645...,2025-11-29 13:26:50.243901,제주시,33.492576,126.501654
3,1574,1272584236,황해식당 제주공항 갈치,"해물,생선요리",제주 제주시 일주서로 7682 황해식당 제주공항 갈치,010-5822-9737,4.7,11631,5000,40000,...,True,False,True,False,영업 종료\n10:00에 영업 시작\n10시 0분에 영업 시작,https://m.place.naver.com/restaurant/127258423...,2025-11-29 13:26:50.243901,제주시,33.493821,126.467176
4,1575,1326771119,찰리공장 제주동문시장본점,"카페,디저트",제주 제주시 중앙로13길 21 찰리공장 제주동문시장본점,,NaN,23996,2500,26000,...,False,False,True,False,영업 중\n21:00에 영업 종료\n21시 0분에 영업 종료,https://m.place.naver.com/restaurant/132677111...,2025-11-29 13:26:50.243901,제주시,33.511572,126.526739
5,1576,1353910623,성심조림 제주공항점,한식,제주 제주시 신광로 8 1층,,1.0,1957,12000,40000,...,False,True,True,False,영업 중\n21:00에 라스트오더\n21시 0분에 라스트오더,https://m.place.naver.com/restaurant/135391062...,2025-11-29 13:26:50.243901,제주시,33.491486,126.489952
6,1578,1131070854,이재모피자 제주점,피자,제주 제주시 간월동로 6 이재모피자 제주점,,1.0,1187,25000,37000,...,False,False,False,False,영업 중\n20:30에 라스트오더\n20시 30분에 라스트오더,https://m.place.naver.com/restaurant/113107085...,2025-11-29 13:26:50.243901,제주시,33.485030,126.543511
7,1579,2014164507,품앗이 제주시청점,요리주점,제주 제주시 서광로28길 50 1층,,NaN,107,48000,72000,...,False,False,True,False,영업 중\n00:00에 라스트오더\n0시 0분에 라스트오더,https://m.place.naver.com/restaurant/201416450...,2025-11-29 13:26:50.243901,제주시,33.496938,126.528979
8,1581,1582318900,카페 나모나모 베이커리,"카페,디저트",제주 제주시 도두봉6길 4,,5.0,5713,5000,9000,...,True,False,False,False,영업 중\n20:30에 라스트오더\n20시 30분에 라스트오더,https://m.place.naver.com/restaurant/158231890...,2025-11-29 13:26:50.243901,제주시,33.508905,126.471952
9,1582,38265405,고집돌우럭 제주공항점,향토음식,제주 제주시 임항로 30,,NaN,17113,24000,33000,...,True,False,True,False,영업 중\n21:30에 영업 종료\n21시 30분에 영업 종료,https://m.place.naver.com/restaurant/38265405/...,2025-11-29 13:26:50.243901,제주시,33.516258,126.528057

=== menus 테이블 ===
총 1297개 메뉴

     id  place_id              name  price category
0  2947      1559            제주갈비한판  65000       메인
1  2948      1559             도대표한판  69000       메인
2  2949      1559          고기폭탄된장술밥  10000       단품
3  2950      1559            꽃멸젓볶음밥   9000       단품
4  2951      1559       흑도목 (흑돼지목살)  22000       메인
5  2952      1559  도갈비 (목살+등갈비 8:2)  22000       메인
6  2953      1559     도정살 (흑돼지특수부위)  23000       메인
7  2954      1559      흑도겹 (흑돼지오겹살)  22000       메인
8  2955      1559             도대표반판  36000       메인
9  2956      1559          살얼음동동물냉면   8000       단품

=== 통계 ===
카테고리별 장소 수:

  category  cnt
0   카페,디저트  154
1       한식   60
2      생선회   47
3       카페   41
4  해물,생선요리   39
5   돼지고기구이   38
6       국수   29
7     베이커리   26
8     종합분식   23
9  육류,고기요리   17

평점 분포:

   rating_group  cnt
0           1.0   15
1           2.0   13
2           3.0   14
3           4.0   17
4           5.0   42